<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="packages\**" />
    <Compile Remove="Tests\**" />
    <Compile Remove="Test\**" />
    <EmbeddedResource Remove="packages\**" />
    <EmbeddedResource Remove="Tests\**" />
    <EmbeddedResource Remove="Test\**" />
    <None Remove="packages\**" />
    <None Remove="Tests\**" />
    <None Remove="Test\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Autofac" Version="8.3.0" />
    <PackageReference Include="ImpromptuInterface" Version="8.0.6" />
    <PackageReference Include="JetBrains.Annotations" Version="2025.2.2" />
    <PackageReference Include="JetBrains.dotMemoryUnit" Version="3.2.20220510" />
    <PackageReference Include="morelinq" Version="4.4.0" />
  </ItemGroup>

  <ItemGroup>
    <None Update="Singleton\capitals.txt">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
